name: add to jimmu project
on:
  issues:
    types:
      - opened
  label:
    types: [created]

jobs:
  add-to-project:
    name: Add issue to project
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ toJSON(github.event.issue.labels) }}
